// Generated by gencpp from file data_acquisition/Geolocation.msg
// DO NOT EDIT!


#ifndef DATA_ACQUISITION_MESSAGE_GEOLOCATION_H
#define DATA_ACQUISITION_MESSAGE_GEOLOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace data_acquisition
{
template <class ContainerAllocator>
struct Geolocation_
{
  typedef Geolocation_<ContainerAllocator> Type;

  Geolocation_()
    : header()
    , latitude(0.0)
    , longitude(0.0)  {
    }
  Geolocation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::data_acquisition::Geolocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_acquisition::Geolocation_<ContainerAllocator> const> ConstPtr;

}; // struct Geolocation_

typedef ::data_acquisition::Geolocation_<std::allocator<void> > Geolocation;

typedef boost::shared_ptr< ::data_acquisition::Geolocation > GeolocationPtr;
typedef boost::shared_ptr< ::data_acquisition::Geolocation const> GeolocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_acquisition::Geolocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_acquisition::Geolocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::data_acquisition::Geolocation_<ContainerAllocator1> & lhs, const ::data_acquisition::Geolocation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::data_acquisition::Geolocation_<ContainerAllocator1> & lhs, const ::data_acquisition::Geolocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace data_acquisition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::data_acquisition::Geolocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_acquisition::Geolocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_acquisition::Geolocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_acquisition::Geolocation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_acquisition::Geolocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_acquisition::Geolocation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_acquisition::Geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e383d714141551d92fd5b87614818b1c";
  }

  static const char* value(const ::data_acquisition::Geolocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe383d714141551d9ULL;
  static const uint64_t static_value2 = 0x2fd5b87614818b1cULL;
};

template<class ContainerAllocator>
struct DataType< ::data_acquisition::Geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_acquisition/Geolocation";
  }

  static const char* value(const ::data_acquisition::Geolocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_acquisition::Geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 latitude\n"
"float64 longitude\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::data_acquisition::Geolocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_acquisition::Geolocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Geolocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_acquisition::Geolocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_acquisition::Geolocation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_ACQUISITION_MESSAGE_GEOLOCATION_H
