// Generated by gencpp from file data_acquisition/geolocation.msg
// DO NOT EDIT!


#ifndef DATA_ACQUISITION_MESSAGE_GEOLOCATION_H
#define DATA_ACQUISITION_MESSAGE_GEOLOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace data_acquisition
{
template <class ContainerAllocator>
struct geolocation_
{
  typedef geolocation_<ContainerAllocator> Type;

  geolocation_()
    : header()
    , latitute(0.0)
    , longitute(0.0)  {
    }
  geolocation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitute(0.0)
    , longitute(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitute_type;
  _latitute_type latitute;

   typedef double _longitute_type;
  _longitute_type longitute;





  typedef boost::shared_ptr< ::data_acquisition::geolocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_acquisition::geolocation_<ContainerAllocator> const> ConstPtr;

}; // struct geolocation_

typedef ::data_acquisition::geolocation_<std::allocator<void> > geolocation;

typedef boost::shared_ptr< ::data_acquisition::geolocation > geolocationPtr;
typedef boost::shared_ptr< ::data_acquisition::geolocation const> geolocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_acquisition::geolocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_acquisition::geolocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::data_acquisition::geolocation_<ContainerAllocator1> & lhs, const ::data_acquisition::geolocation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.latitute == rhs.latitute &&
    lhs.longitute == rhs.longitute;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::data_acquisition::geolocation_<ContainerAllocator1> & lhs, const ::data_acquisition::geolocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace data_acquisition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::data_acquisition::geolocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_acquisition::geolocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_acquisition::geolocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_acquisition::geolocation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_acquisition::geolocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_acquisition::geolocation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_acquisition::geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68b28efb81f156a5687c93ca2b4a86b3";
  }

  static const char* value(const ::data_acquisition::geolocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68b28efb81f156a5ULL;
  static const uint64_t static_value2 = 0x687c93ca2b4a86b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_acquisition::geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_acquisition/geolocation";
  }

  static const char* value(const ::data_acquisition::geolocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_acquisition::geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 latitute\n"
"float64 longitute\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::data_acquisition::geolocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_acquisition::geolocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitute);
      stream.next(m.longitute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct geolocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_acquisition::geolocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_acquisition::geolocation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitute: ";
    Printer<double>::stream(s, indent + "  ", v.latitute);
    s << indent << "longitute: ";
    Printer<double>::stream(s, indent + "  ", v.longitute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_ACQUISITION_MESSAGE_GEOLOCATION_H
